# Generated by Django 4.2.8 on 2024-01-02 21:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="Ingredients",
            new_name="ingredients",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[400, None],
                upload_to="recipes/",
            ),
        ),
    ]
